FEARS = [
    u"Addiction, substances",
    u"Addiction, money",
    u"Addiction, gambling",
    u"Addiction, sex",
    u"Amnesia, before a certain point (retrograde) or after (anterograde)",
    u"Anxiety",
    u"Bipolar disorder, swings from periods of mania to severe depression",
    u"Borderline Personality Disorder, suicidal, self mutilating behavior",
    u"Dementia",
    u"Dependent Personality Disorder"
    u"Depersonalization Disorder, feelings of unreality, dreamlike state",
    u"Depression",
    u"Histrionic Personality Disorder", 
    u"Hypochondria",
    u"Kleptomania",
    u"Mania",
    u"Masochism",
    u"Multiple Personalities",
    u"Narcissism",
    u"Nymphomania",
    u"Obsessive Compulsive Disorder",
    u"Panic attacks",
    u"Paranoia",
    u"Pyromania",
    u"Sadism",
    u"Schizophrenia, Delusions, hallucinations, and intense paranoia",
    u"Acrophobia, fear of falling", 
    u"Agoraphobia, fear of people", 
    u"Ailurophobia, fear of cats",
    u"Androphobia, fear of men",
    u"Astraphobia, fear of thunder and lightning",
    u"Belonephobia, fear of pine and needles", 
    u"Botanophobia, fear of plants",
    u"Claustrophobia, fear of enclosed spaces", 
    u"Clinophobia, fear of going to bed", 
    u"Demophobia, fear of demons", 
    u"Dendrophobia, fear of trees",
    u"Doraphobia, fear of fur or/and skin", 
    u"Entomophobia, fear of insects", 
    u"Gephydrophobi, fear of of crossing bridges", 
    u"Gynephobia, fear of women",
    u"Hematophobia, fear of blood", 
    u"Monophoibia, fear of solitude", 
    u"Necrophobia, fear of death", 
    u"Pediphobia, fear of children", 
    u"Pyrophobia, fear of fire", 
    u"Scotophobia, fear of darkness", 
    u"Scatophobia, fear of excrements",
    u"Thalassophobia, fear of the sea", 
    u"vestiophobia, fear of cloths", 
    u"Vertigo, fear of hights", 
    u"Xenophobia, fear of foreign things", 
    u"Zoophobia, fear of animals",
]

FEAR_SEVERITY = \
    [u"Leaning" for i in xrange(0, 20)] +\
    [u"Minor" for i in xrange(0, 5)] +\
    [u"Major" for i in xrange(0, 2)] +\
    [u"Overwhelming" for i in xrange(0, 1)]

