HISTORY = [
    u"Enemy",
    u"Friend",
    u"Tragic love affair",
    u"Happy love affair",
    u"Financial loss",
    u"Financial debt",
    u"Financial gain",
    u"Imprisonment",
    u"Illness",
    u"Addiction",
    u"Betrayal",
    u"Accident",
    u"Important other killed",
    u"False accusation",
    u"Hunted by the law",
    u"Hunter by syndicate",
    u"Mental incapacitation",
    u"Physical incapacitation",
    u"Financial windfall ",
    u"Big score",
    u"Mentor",
    u"Faction honorary membership",
    u"Law sympathies",
    u"Syndical sympathies",
    u"Third party sympathies",
    u"Knowledge of some secret",
    u"Good information",
    u"Bad information",
    u"Favour owned by law",
    u"Favour owned by syndicate",
    u"Favour owned by third party",
    u"Emotional lose",
    u"Dependant",
    u"Good reputation",
    u"Bad reputation",
    u"Prestige",
    u"Nomad lifestyle",
    u"Strong religious believes",
    u"Gambling",
    u"Sexual deviancy",
    u"Large family",
    u"Owns a large dwelling",
    u"Owns a powerful vehicle",
    u"Owns a business",
    u"Owns an artefact",
]
